name: pylint
on:
  pull_request:
    branches: [ main ]
    paths-ignore:
    - '**/*.md'
    - '**/*.txt'
    - '**/*.yml'
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements-test.txt ]; then pip install -r requirements-test.txt; fi
    - name: Analysing the code with pylint
      run: |
        find . -type f -name "*.py" | xargs pylint --fail-under 9
