name: pytest

on:
  push:
    branches: [ main ]
    paths-ignore:
    - '**/*.md'
    - '**/*.txt'
    - '**/*.yml'
  pull_request:
    branches: [ main ]
    paths-ignore:
    - '**/*.md'
    - '**/*.txt'
    - '**/*.yml'
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pipenv --user
        pipenv install
    - name:  Run pytests
      run: |
        pytest
